# Road Damage Detection - Part 4: Hyperparameter tuning on Google Colab (YOLOv10s)
Baseline: YOLOv10s + SGD, 40 epochs, imgsz 640, lr0 0.01 (test mAP50-95 = 0.384).
Tuned runs: **T1** 80 epochs (~1.9 h), **T2** imgsz 800 (~1.5 h), **T3** lr0 0.005 (~0.9 h). Run them in this order; stop whenever you want - step 3 evaluates whatever has finished.

Before you start: *Runtime -> Change runtime type -> T4 GPU*. Keep this tab open while training.
Everything is saved to your Google Drive, so if Colab disconnects: *Reconnect*, re-run all cells from the top, and unfinished runs resume automatically.

## 0. Check GPU, mount Google Drive, install

In [1]:
import torch
assert torch.cuda.is_available(), 'No GPU! Runtime -> Change runtime type -> T4 GPU, then re-run.'
print('GPU:', torch.cuda.get_device_name(0))

from google.colab import drive
drive.mount('/content/drive')          # click Allow when asked
!pip install -q ultralytics roboflow

GPU: Tesla T4
Mounted at /content/drive

## 1. Download the dataset (asks for your Roboflow API key)

In [2]:
import gc, yaml, shutil
import numpy as np, pandas as pd
from pathlib import Path
from getpass import getpass
from roboflow import Roboflow
from ultralytics import YOLO

DATA_DIR = Path('/content/road-damage')
if not (DATA_DIR / 'data.yaml').exists():
    try:
        from google.colab import userdata
        key = userdata.get('ROBOFLOW_API_KEY')
    except Exception:
        key = getpass('Paste your Roboflow API key and press Enter: ')
    rf = Roboflow(api_key=key)
    rf.workspace('mazen-ayad').project('road-damage-l1ju7-g2jni').version(1).download('yolov8', location=str(DATA_DIR))

cfg = yaml.safe_load(open(DATA_DIR / 'data.yaml'))
cfg.update(path=str(DATA_DIR), train='train/images', val='valid/images', test='test/images')
yaml.safe_dump(cfg, open(DATA_DIR / 'data.yaml', 'w'))
DATA_YAML = str(DATA_DIR / 'data.yaml')
print('Dataset ready:', DATA_YAML)

Creating new Ultralytics Settings v0.0.8 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/usage/settings.
Paste your Roboflow API key and press Enter: ··········
loading Roboflow workspace...
loading Roboflow project...

Downloading Dataset Version Zip in /content/road-damage to yolov8:: 100%|██████████| 2130839/2130839 [00:31<00:00, 67213.77it/s]

Extracting Dataset Version Zip to /content/road-damage in yolov8:: 100%|██████████| 13518/13518 [00:14<00:00, 930.06it/s]

Dataset ready: /content/road-damage/data.yaml

## 2. Settings and the training helper

In [3]:
RUNS = Path('/content/drive/MyDrive/road_damage_runs_tuned')   # saved on Google Drive
RUNS.mkdir(parents=True, exist_ok=True)

BASE = dict(data=DATA_YAML, optimizer='SGD', lr0=0.01, imgsz=640, batch=16, workers=2, seed=0,
            project=str(RUNS), exist_ok=True, plots=True, device=0)

def train_tuned(name, weights, **overrides):
    """Train one run. Skips finished runs, resumes interrupted ones, never stops the notebook on error."""
    d = RUNS / name
    if (d / 'DONE').exists():
        print('Already done, skipping:', name); return
    gc.collect(); torch.cuda.empty_cache()
    try:
        last = d / 'weights' / 'last.pt'
        if last.exists():
            print('Resuming interrupted run:', name)
            YOLO(str(last)).train(resume=True)
        else:
            YOLO(weights).train(name=name, **{**BASE, **overrides})
        (d / 'DONE').write_text('ok')
    except Exception as e:
        print(f'!!! {name} FAILED: {e!r}')

## Run T1: 80 epochs (about 1.9 h)

In [4]:
train_tuned('v10s_sgd_e80', 'yolov10s.pt', epochs=80, patience=20)

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov10s.pt to 'yolov10s.pt': 100% ━━━━━━━━━━━━ 15.9MB 89.5MB/s 0.2s
Ultralytics 8.4.191 🚀 Python-3.13.16 torch-2.11.0+cu130 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/road-damage/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=80, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov10s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=v10s_sgd_e80, nbs=64, nms=None, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/road_damage_runs_tuned, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/road_damage_runs_tuned/v10s_sgd_e80, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 21.3MB/s 0.0s
Overriding model.yaml nc=80 with nc=7

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1     36096  ultralytics.nn.modules.block.SCDown          [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1    137728  ultralytics.nn.modules.block.SCDown          [256, 512, 3, 2]
  8                  -1  1    958464  ultralytics.nn.modules.block.C2fCIB          [512, 512, 1, True, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.PSA             [512, 512]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 20                  -1  1     68864  ultralytics.nn.modules.block.SCDown          [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1089536  ultralytics.nn.modules.block.C2fCIB          [768, 512, 1, True, True]
 23        [16, 19, 22]  1   1644218  ultralytics.nn.modules.head.v10Detect        [7, [128, 256, 512]]
YOLOv10s summary: 234 layers, 8,071,770 parameters, 8,071,754 gradients, 24.9 GFLOPs

Transferred 607/619 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: downloading yolo26n.pt for AMP checks (one-time, not used for training)...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'weights/yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 94.6MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 841.7±523.9 MB/s, size: 193.8 KB)
train: Scanning /content/road-damage/train/labels... 4930 images, 0 backgrounds, 5 corrupt: 100% ━━━━━━━━━━━━ 4930/4930 1.9Kit/s 2.6s
train: /content/road-damage/train/images/105_jpg.rf.3716b080c38ebfab3d480df522539cab.jpg: ignoring corrupt image/label: labels mix segment and detection rows
train: /content/road-damage/train/images/12_jpg.rf.05f591db68946c299f22c1ba74cf4671.jpg: ignoring corrupt image/label: labels mix segment and detection rows
train: /content/road-damage/train/images/265_jpg.rf.ba6c625175e5f1c69b86facb17b260a3.jpg: ignoring corrupt image/label: labels mix segment and detection rows
train: /content/road-damage/train/images/img-892-_jpg.rf.6ffda321581dd361faff795a30ea3aee.jpg: ignoring corrupt image/label: labels mix segment and detection rows
train: /content/road-damage/train/images/img-921-_jpg.rf.e80ce930b4625edc8e89928ad51cc130.jpg: ignoring corrupt image/label: labels mix segment and detection rows
train: New cache created: /content/road-damage/train/labels.cache
WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 59, len(boxes) = 15004. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2679.5±957.5 MB/s, size: 318.5 KB)
val: Scanning /content/road-damage/valid/labels... 1146 images, 0 backgrounds, 4 corrupt: 100% ━━━━━━━━━━━━ 1146/1146 2.0Kit/s 0.6s
val: /content/road-damage/valid/images/21_jpg.rf.7c82427ce016b68e188dd759d0562e4b.jpg: ignoring corrupt image/label: labels mix segment and detection rows
val: /content/road-damage/valid/images/img-243-_jpg.rf.41bcafc69fdca98a8a7f6fad3a31f03f.jpg: ignoring corrupt image/label: labels mix segment and detection rows
val: /content/road-damage/valid/images/img-249-_jpg.rf.9107ff651b4057ea648e72dea0bca5e2.jpg: ignoring corrupt image/label: labels mix segment and detection rows
val: /content/road-damage/valid/images/img-25-_jpg.rf.e5d4f51e266d2ab3b00b7b3928def8e0.jpg: ignoring corrupt image/label: labels mix segment and detection rows
val: New cache created: /content/road-damage/valid/labels.cache
WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 15, len(boxes) = 3570. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 99 weight(decay=0.0), 112 weight(decay=0.0005), 111 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/road_damage_runs_tuned/v10s_sgd_e80/labels.jpg...
Using 4925 train, 1142 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/road_damage_runs_tuned/v10s_sgd_e80
Starting training for 80 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/80      4.75G      1.833      4.319      1.666         61        640: 100% ━━━━━━━━━━━━ 308/308 2.5it/s 2:05
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 1.8it/s 19.6s
                   all       1142       3570      0.485      0.188      0.152     0.0774

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/80      6.68G      1.812      2.787       1.59         90        640: 100% ━━━━━━━━━━━━ 308/308 2.6it/s 1:56
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.5s
                   all       1142       3570       0.46       0.22      0.176     0.0919

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/80      6.68G      1.917      2.859      1.666         94        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.4s
                   all       1142       3570      0.193      0.158     0.0995     0.0471

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/80      6.68G      1.978      2.976       1.71         59        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:55
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.3s
                   all       1142       3570      0.163      0.141     0.0918      0.041

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/80      6.68G      1.959      2.889        1.7         72        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.4s
                   all       1142       3570      0.199      0.187      0.152      0.073

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/80      6.68G      1.936      2.793      1.672         61        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.0it/s 18.0s
                   all       1142       3570      0.344      0.206      0.189     0.0965

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/80      6.68G      1.918      2.735      1.666         78        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.3s
                   all       1142       3570      0.297      0.269      0.234      0.126

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/80      6.68G      1.888      2.662      1.658         76        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.2s
                   all       1142       3570      0.251      0.224      0.183     0.0938

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/80      6.68G      1.856      2.627      1.635         88        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.0s
                   all       1142       3570      0.302      0.271       0.24      0.125

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/80      6.68G      1.865      2.582      1.637         75        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.4s
                   all       1142       3570      0.311      0.262      0.228      0.125

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/80      6.68G      1.836      2.534      1.615         81        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.3s
                   all       1142       3570      0.304      0.302      0.266      0.144

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/80      6.68G      1.814       2.48      1.615         51        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.0s
                   all       1142       3570      0.313       0.28      0.235      0.123

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/80      6.68G      1.818       2.46      1.592         76        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 16.9s
                   all       1142       3570      0.339      0.243      0.228      0.126

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/80      6.68G      1.806      2.439      1.579         63        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:50
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.4s
                   all       1142       3570      0.351      0.305       0.29      0.157

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/80      6.68G      1.788      2.362      1.568         46        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:56
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.0it/s 18.2s
                   all       1142       3570      0.403      0.305      0.299      0.164

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/80      6.68G      1.781      2.363      1.577         91        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:54
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.0it/s 17.7s
                   all       1142       3570      0.366      0.291      0.269      0.147

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/80      6.68G      1.796      2.336      1.592         85        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:54
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.3s
                   all       1142       3570       0.36       0.32      0.316      0.183

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/80      6.68G      1.783      2.307      1.572         76        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.0s
                   all       1142       3570      0.378      0.329       0.33      0.189

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/80      6.68G      1.771      2.279      1.553         73        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:54
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.2s
                   all       1142       3570        0.4      0.317      0.313       0.17

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/80      6.68G      1.745      2.276      1.562         99        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.0it/s 17.6s
                   all       1142       3570      0.375      0.289      0.284      0.157

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/80      6.68G      1.746      2.218      1.538         93        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:54
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.0s
                   all       1142       3570      0.438      0.305       0.33      0.186

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/80      6.68G      1.759      2.196       1.55         73        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:55
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.2it/s 16.7s
                   all       1142       3570      0.403      0.322      0.324      0.177

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/80      6.68G      1.737      2.194      1.554         78        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:54
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.2it/s 16.7s
                   all       1142       3570      0.411      0.356      0.355        0.2

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/80      6.68G      1.736      2.165      1.539         62        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:55
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.0it/s 17.7s
                   all       1142       3570      0.424       0.36      0.365      0.206

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/80      6.68G      1.728      2.134      1.543        109        640: 100% ━━━━━━━━━━━━ 308/308 2.6it/s 1:56
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.0it/s 17.7s
                   all       1142       3570      0.435      0.349      0.362      0.205

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/80      6.68G      1.714      2.123      1.538         85        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:55
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.5s
                   all       1142       3570      0.488      0.325      0.358      0.205

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/80      6.68G      1.704      2.106      1.533         60        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:55
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.1s
                   all       1142       3570      0.434      0.358      0.364      0.202

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/80      6.68G      1.704      2.063      1.526         60        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:55
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.0it/s 17.9s
                   all       1142       3570      0.582      0.369      0.369      0.216

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

## Run T2: image size 800 (about 1.5 h)

In [5]:
train_tuned('v10s_sgd_img800', 'yolov10s.pt', epochs=40, patience=10, imgsz=800, batch=12)

Ultralytics 8.4.191 🚀 Python-3.13.16 torch-2.11.0+cu130 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=12, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/road-damage/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=40, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=800, iou=0.7, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov10s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=v10s_sgd_img800, nbs=64, nms=None, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=10, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/road_damage_runs_tuned, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/road_damage_runs_tuned/v10s_sgd_img800, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=7

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1     36096  ultralytics.nn.modules.block.SCDown          [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1    137728  ultralytics.nn.modules.block.SCDown          [256, 512, 3, 2]
  8                  -1  1    958464  ultralytics.nn.modules.block.C2fCIB          [512, 512, 1, True, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.PSA             [512, 512]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 20                  -1  1     68864  ultralytics.nn.modules.block.SCDown          [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1089536  ultralytics.nn.modules.block.C2fCIB          [768, 512, 1, True, True]
 23        [16, 19, 22]  1   1644218  ultralytics.nn.modules.head.v10Detect        [7, [128, 256, 512]]
YOLOv10s summary: 234 layers, 8,071,770 parameters, 8,071,754 gradients, 24.9 GFLOPs

Transferred 607/619 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1553.8±1410.5 MB/s, size: 193.8 KB)
train: Scanning /content/road-damage/train/labels.cache... 4930 images, 0 backgrounds, 5 corrupt: 100% ━━━━━━━━━━━━ 4930/4930 1.6Git/s 0.0s
train: /content/road-damage/train/images/105_jpg.rf.3716b080c38ebfab3d480df522539cab.jpg: ignoring corrupt image/label: labels mix segment and detection rows
train: /content/road-damage/train/images/12_jpg.rf.05f591db68946c299f22c1ba74cf4671.jpg: ignoring corrupt image/label: labels mix segment and detection rows
train: /content/road-damage/train/images/265_jpg.rf.ba6c625175e5f1c69b86facb17b260a3.jpg: ignoring corrupt image/label: labels mix segment and detection rows
train: /content/road-damage/train/images/img-892-_jpg.rf.6ffda321581dd361faff795a30ea3aee.jpg: ignoring corrupt image/label: labels mix segment and detection rows
train: /content/road-damage/train/images/img-921-_jpg.rf.e80ce930b4625edc8e89928ad51cc130.jpg: ignoring corrupt image/label: labels mix segment and detection rows
WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 59, len(boxes) = 15004. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2271.9±1186.1 MB/s, size: 318.5 KB)
val: Scanning /content/road-damage/valid/labels.cache... 1146 images, 0 backgrounds, 4 corrupt: 100% ━━━━━━━━━━━━ 1146/1146 267.0Mit/s 0.0s
val: /content/road-damage/valid/images/21_jpg.rf.7c82427ce016b68e188dd759d0562e4b.jpg: ignoring corrupt image/label: labels mix segment and detection rows
val: /content/road-damage/valid/images/img-243-_jpg.rf.41bcafc69fdca98a8a7f6fad3a31f03f.jpg: ignoring corrupt image/label: labels mix segment and detection rows
val: /content/road-damage/valid/images/img-249-_jpg.rf.9107ff651b4057ea648e72dea0bca5e2.jpg: ignoring corrupt image/label: labels mix segment and detection rows
val: /content/road-damage/valid/images/img-25-_jpg.rf.e5d4f51e266d2ab3b00b7b3928def8e0.jpg: ignoring corrupt image/label: labels mix segment and detection rows
WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 15, len(boxes) = 3570. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 99 weight(decay=0.0), 112 weight(decay=0.00046875), 111 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/road_damage_runs_tuned/v10s_sgd_img800/labels.jpg...
Using 4925 train, 1142 val images for fraction=1.0 at imgsz=800
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/road_damage_runs_tuned/v10s_sgd_img800
Starting training for 40 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/40      5.68G      1.831      4.609      1.771         21        800: 100% ━━━━━━━━━━━━ 411/411 2.7it/s 2:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.2it/s 21.6s
                   all       1142       3570      0.518      0.166      0.154     0.0785

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/40      5.67G      1.803      2.836      1.681         21        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:26
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.1s
                   all       1142       3570      0.372      0.237      0.145     0.0635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/40      5.62G      1.901      2.927      1.755         21        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:25
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.3it/s 20.5s
                   all       1142       3570     0.0979      0.132     0.0656     0.0273

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/40      5.61G      1.952      3.017      1.822         21        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:26
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.3s
                   all       1142       3570       0.23      0.115     0.0926     0.0423

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/40      5.63G      1.923      2.949      1.776         47        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:24
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.4s
                   all       1142       3570      0.245      0.233      0.177      0.091

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/40      5.64G      1.891      2.885      1.766         23        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:26
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.3s
                   all       1142       3570      0.285      0.178      0.152     0.0724

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/40      5.62G       1.86      2.769      1.739         28        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:25
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.3it/s 20.8s
                   all       1142       3570       0.31       0.22      0.199      0.107

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/40      5.61G      1.842      2.679      1.725         48        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:24
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.1s
                   all       1142       3570      0.343      0.237       0.22       0.12

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/40      5.62G      1.832      2.672      1.718         36        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:29
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.3it/s 20.5s
                   all       1142       3570      0.305      0.267      0.243      0.136

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/40       5.6G      1.809      2.596      1.699         20        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:29
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.2s
                   all       1142       3570       0.31       0.28       0.25      0.132

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/40      5.61G      1.786       2.55      1.678         35        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:28
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.3it/s 20.7s
                   all       1142       3570      0.401       0.27      0.278      0.148

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/40      5.62G      1.759      2.482      1.664         25        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:26
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.3it/s 20.5s
                   all       1142       3570      0.365      0.284      0.275      0.149

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/40      5.59G      1.767      2.459       1.66         35        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:29
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.3it/s 21.2s
                   all       1142       3570      0.293      0.311      0.267      0.142

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/40      5.62G      1.743      2.426      1.662         16        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:27
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.2s
                   all       1142       3570      0.353      0.306      0.302      0.163

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/40      5.63G      1.746      2.368      1.652         35        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:27
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.3it/s 21.0s
                   all       1142       3570      0.356      0.321      0.302      0.165

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/40      5.62G      1.723      2.331      1.637         24        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:26
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.2s
                   all       1142       3570      0.417      0.332      0.332      0.184

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/40      5.63G      1.715       2.29      1.641         21        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:28
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.3it/s 20.6s
                   all       1142       3570      0.368      0.344      0.324      0.177

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/40      5.62G      1.711      2.271      1.623         30        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:28
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 19.8s
                   all       1142       3570      0.402      0.337      0.341      0.188

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/40      5.61G      1.709       2.22      1.627         22        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:27
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.3it/s 20.7s
                   all       1142       3570      0.439      0.358      0.347      0.192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/40      5.62G      1.686        2.2      1.615         26        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:27
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.0s
                   all       1142       3570      0.403      0.326      0.322      0.176

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/40      5.62G      1.687      2.178      1.598         36        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:26
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.3it/s 20.4s
                   all       1142       3570      0.438      0.346      0.357        0.2

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/40      5.62G      1.665      2.126      1.592         36        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:28
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.2s
                   all       1142       3570      0.429      0.374      0.377       0.21

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/40      5.66G      1.663      2.079      1.592         28        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:29
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.3it/s 20.6s
                   all       1142       3570      0.429      0.377      0.376      0.207

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/40      5.58G      1.646      2.048      1.578         40        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:28
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.3it/s 20.8s
                   all       1142       3570       0.45      0.368       0.38      0.217

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/40      5.62G      1.648      2.041      1.578         32        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:28
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.3it/s 20.8s
                   all       1142       3570      0.452      0.378      0.384       0.22

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/40      5.62G      1.622      2.006      1.568         14        800: 100% ━━━━━━━━━━━━ 411/411 2.7it/s 2:31
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.3s
                   all       1142       3570      0.427      0.393      0.385      0.213

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/40      5.61G      1.622      1.983      1.561         43        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:27
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.0s
                   all       1142       3570      0.445      0.406      0.397      0.233

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/40      5.59G      1.606      1.946      1.551         49        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:28
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.2s
                   all       1142       3570      0.423      0.398        0.4      0.228

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/40      5.61G      1.608      1.941      1.549         34        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:27
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.0s
                   all       1142       3570      0.574       0.41      0.402      0.228

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/40      5.61G      1.583       1.89      1.534         19        800: 100% ━━━━━━━━━━━━ 411/411 2.8it/s 2:27
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 2.4it/s 20.3s

## Run T3: lower learning rate 0.005 (about 0.9 h)

In [6]:
train_tuned('v10s_sgd_lr0005', 'yolov10s.pt', epochs=40, patience=10, lr0=0.005)

Ultralytics 8.4.191 🚀 Python-3.13.16 torch-2.11.0+cu130 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/road-damage/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=40, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, kobj=1.0, line_width=None, lr0=0.005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov10s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=v10s_sgd_lr0005, nbs=64, nms=None, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=10, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/road_damage_runs_tuned, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/road_damage_runs_tuned/v10s_sgd_lr0005, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=7

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1     36096  ultralytics.nn.modules.block.SCDown          [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1    137728  ultralytics.nn.modules.block.SCDown          [256, 512, 3, 2]
  8                  -1  1    958464  ultralytics.nn.modules.block.C2fCIB          [512, 512, 1, True, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.PSA             [512, 512]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 20                  -1  1     68864  ultralytics.nn.modules.block.SCDown          [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1089536  ultralytics.nn.modules.block.C2fCIB          [768, 512, 1, True, True]
 23        [16, 19, 22]  1   1644218  ultralytics.nn.modules.head.v10Detect        [7, [128, 256, 512]]
YOLOv10s summary: 234 layers, 8,071,770 parameters, 8,071,754 gradients, 24.9 GFLOPs

Transferred 607/619 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1624.0±1552.4 MB/s, size: 193.8 KB)
train: Scanning /content/road-damage/train/labels.cache... 4930 images, 0 backgrounds, 5 corrupt: 100% ━━━━━━━━━━━━ 4930/4930 1.9Git/s 0.0s
train: /content/road-damage/train/images/105_jpg.rf.3716b080c38ebfab3d480df522539cab.jpg: ignoring corrupt image/label: labels mix segment and detection rows
train: /content/road-damage/train/images/12_jpg.rf.05f591db68946c299f22c1ba74cf4671.jpg: ignoring corrupt image/label: labels mix segment and detection rows
train: /content/road-damage/train/images/265_jpg.rf.ba6c625175e5f1c69b86facb17b260a3.jpg: ignoring corrupt image/label: labels mix segment and detection rows
train: /content/road-damage/train/images/img-892-_jpg.rf.6ffda321581dd361faff795a30ea3aee.jpg: ignoring corrupt image/label: labels mix segment and detection rows
train: /content/road-damage/train/images/img-921-_jpg.rf.e80ce930b4625edc8e89928ad51cc130.jpg: ignoring corrupt image/label: labels mix segment and detection rows
WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 59, len(boxes) = 15004. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2762.3±1323.7 MB/s, size: 318.5 KB)
val: Scanning /content/road-damage/valid/labels.cache... 1146 images, 0 backgrounds, 4 corrupt: 100% ━━━━━━━━━━━━ 1146/1146 84.3Mit/s 0.0s
val: /content/road-damage/valid/images/21_jpg.rf.7c82427ce016b68e188dd759d0562e4b.jpg: ignoring corrupt image/label: labels mix segment and detection rows
val: /content/road-damage/valid/images/img-243-_jpg.rf.41bcafc69fdca98a8a7f6fad3a31f03f.jpg: ignoring corrupt image/label: labels mix segment and detection rows
val: /content/road-damage/valid/images/img-249-_jpg.rf.9107ff651b4057ea648e72dea0bca5e2.jpg: ignoring corrupt image/label: labels mix segment and detection rows
val: /content/road-damage/valid/images/img-25-_jpg.rf.e5d4f51e266d2ab3b00b7b3928def8e0.jpg: ignoring corrupt image/label: labels mix segment and detection rows
WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 15, len(boxes) = 3570. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
optimizer: SGD(lr=0.005, momentum=0.937) with parameter groups 99 weight(decay=0.0), 112 weight(decay=0.0005), 111 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/road_damage_runs_tuned/v10s_sgd_lr0005/labels.jpg...
Using 4925 train, 1142 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/road_damage_runs_tuned/v10s_sgd_lr0005
Starting training for 40 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/40      4.73G      1.863      4.786      1.704         61        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:55
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.0it/s 17.7s
                   all       1142       3570      0.421       0.16      0.157     0.0697

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/40      6.66G      1.745      2.849      1.554         90        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.0it/s 17.7s
                   all       1142       3570      0.471      0.231      0.209      0.111

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/40      6.67G      1.803      2.657      1.575         94        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.0it/s 17.6s
                   all       1142       3570      0.384       0.19      0.169      0.076

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/40      6.67G      1.864      2.644      1.611         59        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:51
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.5s
                   all       1142       3570      0.347      0.245      0.228      0.117

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/40      6.67G      1.858      2.584      1.613         72        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.3s
                   all       1142       3570        0.2      0.185       0.14       0.07

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/40      6.67G      1.849      2.528      1.616         61        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.3s
                   all       1142       3570      0.291      0.255      0.224      0.117

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/40      6.67G      1.828      2.489      1.594         78        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:51
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.0it/s 17.8s
                   all       1142       3570      0.371      0.292      0.278      0.151

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/40      6.67G      1.814      2.416      1.586         76        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.3s
                   all       1142       3570      0.321      0.302      0.275      0.155

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/40      6.67G      1.788      2.359      1.567         88        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.2s
                   all       1142       3570      0.358       0.31      0.296      0.158

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/40      6.67G      1.786      2.344      1.551         75        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.2s
                   all       1142       3570      0.375       0.31      0.297      0.163

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/40      6.67G       1.77      2.299      1.553         81        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.4s
                   all       1142       3570       0.42      0.313      0.324      0.184

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/40      6.67G      1.744       2.23      1.542         51        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.0it/s 17.7s
                   all       1142       3570      0.374      0.305      0.305      0.166

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/40      6.67G      1.754      2.212      1.534         76        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.3s
                   all       1142       3570      0.393       0.29      0.294      0.167

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/40      6.67G      1.744      2.198      1.514         63        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:51
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.2it/s 16.7s
                   all       1142       3570      0.398      0.335      0.326      0.183

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/40      6.67G      1.725      2.119      1.499         46        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.5s
                   all       1142       3570      0.404      0.366      0.354      0.198

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/40      6.67G      1.712      2.111      1.507         91        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.0it/s 18.4s
                   all       1142       3570      0.569      0.364      0.364      0.207

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/40      6.67G      1.717       2.09      1.506         85        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:55
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 16.9s
                   all       1142       3570      0.567      0.374      0.371       0.21

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/40      6.67G      1.704      2.044      1.481         76        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.3s
                   all       1142       3570      0.407      0.371      0.375      0.212

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/40      6.67G      1.691       2.01      1.478         73        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 16.8s
                   all       1142       3570      0.579      0.369      0.374      0.211

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/40      6.67G      1.666      2.009      1.487         99        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.4s
                   all       1142       3570      0.607      0.362      0.383      0.221

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/40      6.67G      1.663      1.945      1.469         93        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.2it/s 16.7s
                   all       1142       3570      0.609      0.371      0.392       0.22

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/40      6.67G      1.657      1.921      1.461         73        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.2it/s 16.5s
                   all       1142       3570      0.461      0.398      0.402      0.235

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/40      6.67G      1.637       1.91      1.457         78        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.2it/s 16.4s
                   all       1142       3570      0.588      0.397      0.399      0.231

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/40      6.67G      1.629      1.875      1.451         62        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:51
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.1s
                   all       1142       3570      0.608      0.393      0.403      0.232

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/40      6.67G      1.622      1.853      1.439        109        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:51
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 16.8s
                   all       1142       3570      0.611      0.393      0.407      0.243

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/40      6.67G      1.598      1.826      1.435         85        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:51
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.3s
                   all       1142       3570      0.626      0.398      0.407      0.238

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/40      6.67G      1.593      1.802       1.43         60        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:50
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.2s
                   all       1142       3570       0.59      0.415      0.415      0.238

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/40      6.67G      1.586      1.761      1.421         60        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:51
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.2s
                   all       1142       3570      0.584      0.418      0.417      0.243

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/40      6.67G      1.572      1.735      1.418         79        640: 100% ━━━━━━━━━━━━ 308/308 2.8it/s 1:51
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 16.8s
                   all       1142       3570      0.604      0.419      0.428       0.25

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/40      6.67G      1.564      1.695      1.407        102        640: 100% ━━━━━━━━━━━━ 308/308 2.7it/s 1:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 2.1it/s 17.1s

## 3. Evaluate every finished run on the TEST set + save results

In [7]:
TEST_IMGS = sorted((DATA_DIR / 'test' / 'images').glob('*'))
rows, per_class = [], {}

for d in sorted(RUNS.glob('v*_*')):
    if not (d / 'DONE').exists():
        continue
    name = d.name
    w = d / 'weights' / 'best.pt'
    imgsz = int(yaml.safe_load(open(d / 'args.yaml'))['imgsz'])
    hist = pd.read_csv(d / 'results.csv'); hist.columns = [c.strip() for c in hist.columns]
    gc.collect(); torch.cuda.empty_cache()

    m = YOLO(str(w)).val(data=DATA_YAML, split='test', imgsz=imgsz, batch=8, conf=0.001, plots=False,
                         project='/content/test_eval', name=name, exist_ok=True, verbose=False, device=0)
    per_class[name] = {m.names[c]: float(m.box.ap50[i]) for i, c in enumerate(m.box.ap_class_index)}

    mdl, t = YOLO(str(w)), []
    for p in TEST_IMGS[:110]:
        r = mdl.predict(str(p), imgsz=imgsz, conf=0.25, device=0, verbose=False)[0]
        t.append(sum(r.speed.values()))
    rows.append(dict(run=name, imgsz=imgsz, epochs_done=len(hist),
                     val_mAP50_95=hist['metrics/mAP50-95(B)'].max(),
                     precision=m.box.mp, recall=m.box.mr, mAP50=m.box.map50, mAP50_95=m.box.map,
                     GPU_FPS_total=1000 / np.mean(t[10:]), size_MB=w.stat().st_size / 1e6))

res = pd.DataFrame(rows).round(3)
# reference row = the earlier baseline (copied from the previous Kaggle test evaluation)
baseline = dict(run='v10s_sgd (baseline, 40 ep)', imgsz=640, epochs_done=40, val_mAP50_95=0.256,
                precision=0.597, recall=0.595, mAP50=0.612, mAP50_95=0.384, GPU_FPS_total=96.7, size_MB=16.5)
res = pd.concat([pd.DataFrame([baseline]), res], ignore_index=True)
res.to_csv(RUNS / 'tuning_results.csv', index=False)
pc = pd.DataFrame(per_class).round(3); pc.to_csv(RUNS / 'tuning_per_class_AP50.csv')
display(res); display(pc)

out = Path('/content/tuned_weights'); out.mkdir(exist_ok=True)
for d in RUNS.glob('v*_*'):
    if (d / 'DONE').exists():
        shutil.copy(d / 'weights' / 'best.pt', out / f'{d.name}.pt')
shutil.make_archive(str(RUNS / 'tuned_weights'), 'zip', out)
print('Saved in your Google Drive folder road_damage_runs_tuned: tuning_results.csv, tuning_per_class_AP50.csv, tuned_weights.zip')

Ultralytics 8.4.191 🚀 Python-3.13.16 torch-2.11.0+cu130 CUDA:0 (Tesla T4, 14913MiB)
YOLOv10s summary (fused): 103 layers, 7,220,709 parameters, 0 gradients, 21.5 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 730.5±1546.2 MB/s, size: 249.1 KB)
val: Scanning /content/road-damage/test/labels... 681 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 681/681 662.8it/s 1.0s
val: New cache created: /content/road-damage/test/labels.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 86/86 7.3it/s 11.8s
                   all        681       2004      0.598      0.599        0.6      0.376
Speed: 0.9ms preprocess, 9.6ms inference, 0.0ms loss, 1.2ms postprocess per image
Ultralytics 8.4.191 🚀 Python-3.13.16 torch-2.11.0+cu130 CUDA:0 (Tesla T4, 14913MiB)
YOLOv10s summary (fused): 103 layers, 7,220,709 parameters, 0 gradients, 21.5 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2314.4±824.3 MB/s, size: 159.2 KB)
val: Scanning /content/road-damage/test/labels.cache... 681 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 681/681 259.7Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 86/86 5.6it/s 15.3s
                   all        681       2004      0.607      0.577       0.61      0.377
Speed: 1.4ms preprocess, 15.0ms inference, 0.0ms loss, 1.3ms postprocess per image
Ultralytics 8.4.191 🚀 Python-3.13.16 torch-2.11.0+cu130 CUDA:0 (Tesla T4, 14913MiB)
YOLOv10s summary (fused): 103 layers, 7,220,709 parameters, 0 gradients, 21.5 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2234.0±1119.4 MB/s, size: 304.3 KB)
val: Scanning /content/road-damage/test/labels.cache... 681 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 681/681 219.7Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 86/86 7.5it/s 11.5s
                   all        681       2004        0.6      0.621      0.621       0.39
Speed: 0.9ms preprocess, 9.3ms inference, 0.0ms loss, 1.3ms postprocess per image

,run,imgsz,epochs_done,val_mAP50_95,precision,recall,mAP50,mAP50_95,GPU_FPS_total,size_MB
0,"v10s_sgd (baseline, 40 ep)",640,40,0.256,0.597,0.595,0.612,0.384,96.700,16.500
1,v10s_sgd_e80,640,80,0.253,0.598,0.599,0.600,0.376,69.378,16.526
2,v10s_sgd_img800,800,40,0.251,0.607,0.577,0.610,0.377,46.274,16.544
3,v10s_sgd_lr0005,640,40,0.259,0.600,0.621,0.621,0.390,73.447,16.520

              v10s_sgd_e80  v10s_sgd_img800  v10s_sgd_lr0005
alligator            0.356            0.378            0.361
block                0.868            0.852            0.889
crack                0.789            0.861            0.859
longitudinal         0.223            0.267            0.268
pothole              0.694            0.711            0.693
transverse           0.671            0.592            0.657

Saved in your Google Drive folder road_damage_runs_tuned: tuning_results.csv, tuning_per_class_AP50.csv, tuned_weights.zip